### PR TITLE
bump flink intercommunication cert duration to 3 years

### PR DESCRIPTION
**Pull request by cthtrifork**

### CODE REVIEW

**Review by AndersBennedsgaard — COMMENTED** [review]
Would you mind making it configurable?

Also, 3y seems like a pretty high default?

**Comment by cthtrifork** [comment]
> Would you mind making it configurable?
> 
> Also, 3y seems like a pretty high default?

We are not using the certificate for other reasons than intercommunication between a single job manager and task manager and to ensure encryption.
When a certificate expires and if the task manager is restarted, then the job manager will fail untill manually restarted

I am not able to think of an arguement for making the period shorter or configurable. What do you think?

**Comment by AndersBennedsgaard** [comment]
> We are not using the certificate for other reasons than intercommunication between a single job manager and task manager and to ensure encryption. When a certificate expires and if the task manager is restarted, then the job manager will fail untill manually restarted
> 
> I am not able to think of an arguement for making the period shorter or configurable. What do you think?

Customers and users have very different demands on how often certificates should expire and be renewed, so this alone should be enough.

But also, the point of any templating engines is that stuff should be easy to configure how you like it to, so as much as possible should be made configurable. At those very specific times where you need to change something very specific, it is better to just have the possibility to just do it instead of having to make changes to the chart. As an example, when we discovered that the Service resource must have the `appProtocol=http` when using Istio, it took a long time to get this fix around to all clusters, since it required changing the chart instead of just communicating it to developers that they needed to set it

**Review by mbjtrifork — COMMENTED** [review]
I agree with Anders here, better to put the defaults in the values.yaml and allowing for override

**Review by AndersBennedsgaard — APPROVED** [review]
I've left a small optional remark. Other than that, it LGTM

**Review by mbjtrifork — APPROVED** [review]

**Pull request merged**
